### ISSUE TITLE
issue with `tonic` template 

### ISSUE THREAD

**Issue by lamiazar** [socketsupply/create-socket-app#19]
When I run `npm create socket-app tonic` ,I'm getting a `401` error : 
```
lamia@lamia-pc:~/Desktop/my-app$ npm create socket-app tonic
Initializing npm package...OK
Installing developer dependencies...OK
Installing dependencies...
Unable to run npm install: Error: Command failed: npm install @socketsupply/tonic --save
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/@socketsupply%2ftonic - unauthenticated: User cannot be authenticated with the token provided.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lamia/.npm/_logs/2023-02-20T20_20_58_482Z-debug-0.log

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm ERR! code 1
npm ERR! path /home/lamia/Desktop/my-app
npm ERR! command failed
npm ERR! command sh -c -- create-socket-app tonic

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lamia/.npm/_logs/2023-02-20T20_20_55_693Z-debug-0.log
```
But the same `token` is working  for all the other templates.

**Comment by chicoxyzzy** [comment]
It's probably `@socketsupply:registry=https://npm.pkg.github.com/` in your `~/.npmrc`

**Comment by lamiazar** [comment]
> It's probably @socketsupply:registry=https://npm.pkg.github.com/ in your ~/.npmrc
yes, correct.

**Comment by chicoxyzzy** [comment]
> yes, correct.

 I think we can close this one than. Usually users don't have this line in their `~/.npmrc`, It's our custom config option to get a package from the GitHub registry

**Comment by chicoxyzzy** [comment]
BTW you probably can ask @heapwolf or @jwerle to give you a read permission for the `@socketsupply/tonic` package, so you won't have this issue using GH registry

**Comment by jwerle** [comment]
> BTW you probably can ask @heapwolf or @jwerle to give you a read permission for the `@socketsupply/tonic` package, so you won't have this issue using GH registry

hmm its public so you should already, but I added @socketsupply/qa to the https://github.com/socketsupply/tonic repo just in case

**Comment by heapwolf** [comment]
@lamiazar can you test this and close the issue if it works?

**Comment by lamiazar** [comment]
I have another error now (I updated my token and commented out the `@socketsupply` line) :
```
lamia@lamia-pc:~/Desktop/my-app$ yarn create socket-app tonic
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 418ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 0s 458ms

Initializing npm package...OK
Installing developer dependencies...
Unable to run npm install: Error: Command failed: npm install -D esbuild
npm ERR! code 1
npm ERR! path /home/lamia/Desktop/my-app/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! node:internal/errors:857
npm ERR!   const err = new Error(message);
npm ERR!               ^
npm ERR! 
npm ERR! Error: Command failed: /usr/bin/node /home/lamia/Desktop/my-app/node_modules/esbuild/bin/esbuild --version
npm ERR! node:internal/errors:478
npm ERR!     ErrorCaptureStackTrace(err);
npm ERR!     ^
npm ERR! 
npm ERR! TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /home/lamia/Desktop/my-app/node_modules/esbuild/bin/esbuild
npm ERR!     at new NodeError (node:internal/errors:387:5)
npm ERR!     at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:75:11)
npm ERR!     at defaultGetFormat (node:internal/modules/esm/get_format:117:38)
npm ERR!     at defaultLoad (node:internal/modules/esm/load:81:20)
npm ERR!     at nextLoad (node:internal/modules/esm/loader:163:28)
npm ERR!     at load$1 (file:///tmp/xfs-8da86f23/dlx-4908/.pnp.loader.mjs:1455:12)
npm ERR!     at nextLoad (node:internal/modules/esm/loader:163:28)
npm ERR!     at ESMLoader.load (node:internal/modules/esm/loader:605:26)
npm ERR!     at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
npm ERR!     at new ModuleJob (node:internal/modules/esm/module_job:63:26) {
npm ERR!   code: 'ERR_UNKNOWN_FILE_EXTENSION'
npm ERR! }
npm ERR! 
npm ERR!     at checkExecSyncError (node:child_process:861:11)
npm ERR!     at Object.execFileSync (node:child_process:896:15)
npm ERR!     at validateBinaryVersion (/home/lamia/Desktop/my-app/node_modules/esbuild/install.js:97:28)
npm ERR!     at /home/lamia/Desktop/my-app/node_modules/esbuild/install.js:282:5 {
npm ERR!   status: 1,
npm ERR!   signal: null,
npm ERR!   output: [
npm ERR!     null,
npm ERR!     Buffer(0) [Uint8Array] [],
npm ERR!     Buffer(906) [Uint8Array] [
npm ERR!       110, 111, 100, 101,  58, 105, 110, 116, 101, 114, 110,  97,
npm ERR!       108,  47, 101, 114, 114, 111, 114, 115,  58,  52,  55,  56,
npm ERR!        10,  32,  32,  32,  32,  69, 114, 114, 111, 114,  67,  97,
npm ERR!       112, 116, 117, 114, 101,  83, 116,  97,  99, 107,  84, 114,
npm ERR!        97,  99, 101,  40, 101, 114, 114,  41,  59,  10,  32,  32,
npm ERR!        32,  32,  94,  10,  10,  84, 121, 112, 101,  69, 114, 114,
npm ERR!       111, 114,  32,  91,  69,  82,  82,  95,  85,  78,  75,  78,
npm ERR!        79,  87,  78,  95,  70,  73,  76,  69,  95,  69,  88,  84,
npm ERR!        69,  78,  83,  73,
npm ERR!       ... 806 more items
npm ERR!     ]
npm ERR!   ],
npm ERR!   pid: 4991,
npm ERR!   stdout: Buffer(0) [Uint8Array] [],
npm ERR!   stderr: Buffer(906) [Uint8Array] [
npm ERR!     110, 111, 100, 101,  58, 105, 110, 116, 101, 114, 110,  97,
npm ERR!     108,  47, 101, 114, 114, 111, 114, 115,  58,  52,  55,  56,
npm ERR!      10,  32,  32,  32,  32,  69, 114, 114, 111, 114,  67,  97,
npm ERR!     112, 116, 117, 114, 101,  83, 116,  97,  99, 107,  84, 114,
npm ERR!      97,  99, 101,  40, 101, 114, 114,  41,  59,  10,  32,  32,
npm ERR!      32,  32,  94,  10,  10,  84, 121, 112, 101,  69, 114, 114,
npm ERR!     111, 114,  32,  91,  69,  82,  82,  95,  85,  78,  75,  78,
npm ERR!      79,  87,  78,  95,  70,  73,  76,  69,  95,  69,  88,  84,
npm ERR!      69,  78,  83,  73,
npm ERR!     ... 806 more items
npm ERR!   ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lamia/.npm/_logs/2023-02-21T14_06_20_032Z-debug-0.log

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

**Comment by chicoxyzzy** [comment]
Note: it only fails on yarn 3.*. Works fine on yarn 1.

**Comment by lamiazar** [comment]
> Note: it only fails on yarn 3.*. Works fine on yarn 1.

Correct :
```
rahimbedjou@Raheems-MacBook desktop % cd my-app
rahimbedjou@Raheems-MacBook my-app % yarn create socket-app tonic
yarn create v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-socket-app@1.0.11" with binaries:
      - create-socket-app
[####] 4/4
The current directory is not empty
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-socket-app
Arguments: tonic
Directory: /Users/rahimbedjou/Desktop/my-app
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
rahimbedjou@Raheems-MacBook my-app % cd ..
rahimbedjou@Raheems-MacBook .Trash % cd ..
rahimbedjou@Raheems-MacBook rahimbedjou % cd ~/desktop
rahimbedjou@Raheems-MacBook desktop % cd app 
rahimbedjou@Raheems-MacBook app % yarn create socket-app tonic
yarn create v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-socket-app@1.0.11" with binaries:
      - create-socket-app
[####] 4/4Initializing npm package...OK
Installing developer dependencies...OK
Installing dependencies...OK
Adding package scripts...OK
Creating socket files...OK
Updating project configuration...OK
Copying project boilerplate...OK

Type 'npm start' to launch the app
✨  Done in 12.99s.
```

**Comment by lamiazar** [comment]
I'll open an issue about `yarn v 3` support.

**Comment by lamiazar** [comment]
This is just an issue with `v 3` I already opened an issue here -->#22
