### ISSUE TITLE
install ssc via npm

### ISSUE THREAD

**Issue by heapwolf** [socketsupply/create-socket-app#2]
if ssc is not installed we should install it from [here](https://github.com/socketsupply/create-socket-app/blob/main/index.js#L19-L20) with maybe something like [this](https://github.com/socketsupply/create-socket-app/blob/main/index.js#L115-L130) when the user runs the command `npx crete-socket-app`.

**Comment by Anoesj** [comment]
Not sure if this is related to this question, but when running `pnpm create socket-app vue`, I got this output:

```
.../share/pnpm/store/v3/tmp/dlx-10957    | Progress: resolved 1, reused 0, downl.../share/pnpm/store/v3/tmp/dlx-10957    |   +1 +
.../share/pnpm/store/v3/tmp/dlx-10957    | Progress: resolved 1, reused 0, downl.../share/pnpm/store/v3/tmp/dlx-10957    | Progress: resolved 1, reused 0, downlPackages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/user/.local/share/pnpm/store/v3
  Virtual store is at:             ../../../home/user/.local/share/pnpm/store/v3/tmp/dlx-10957/node_modules/.pnpm
.../share/pnpm/store/v3/tmp/dlx-10957    | Progress: resolved 1, reused 0, downloaded 1, added 0

Creating socket files...
Unable to create socket files: Error: Command failed: ssc init
/bin/sh: 1: ssc: not found

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:320:12)
OK                         .../share/pnpm/store/v3/tmp/dlx-10957    | Progress: resolved 1, reused 0, downloaded 1, added 1, done
OK
Installing developer dependencies...
Installing dependencies...OK
Adding package scripts...OK
Updating project configuration...
Unable to read socket.ini: Error: ENOENT: no such file or directory, open 'socket.ini'
 ERROR  Command failed with exit code 1: create-socket-app vue

pnpm: Command failed with exit code 1: create-socket-app vue
    at makeError (/home/user/.local/share/pnpm/global/5/.pnpm/pnpm@7.26.2/node_modules/pnpm/dist/pnpm.cjs:23105:17)
    at handlePromise (/home/user/.local/share/pnpm/global/5/.pnpm/pnpm@7.26.2/node_modules/pnpm/dist/pnpm.cjs:23676:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (/home/user/.local/share/pnpm/global/5/.pnpm/pnpm@7.26.2/node_modules/pnpm/dist/pnpm.cjs:217528:7)
    at async /home/user/.local/share/pnpm/global/5/.pnpm/pnpm@7.26.2/node_modules/pnpm/dist/pnpm.cjs:225120:21
    at async main (/home/user/.local/share/pnpm/global/5/.pnpm/pnpm@7.26.2/node_modules/pnpm/dist/pnpm.cjs:225089:34)
    at async runPnpm (/home/user/.local/share/pnpm/global/5/.pnpm/pnpm@7.26.2/node_modules/pnpm/dist/pnpm.cjs:225319:5)
    at async /home/user/.local/share/pnpm/global/5/.pnpm/pnpm@7.26.2/node_modules/pnpm/dist/pnpm.cjs:225311:7
```
Looks like [this line](https://github.com/socketsupply/create-socket-app/blob/main/index.js#L71) explains that when ssc is not installed, it should install it using [the install function](https://github.com/socketsupply/create-socket-app/blob/main/index.js#L22), but this function is still empty.

**Comment by chicoxyzzy** [comment]
Yes, we don't install `ssc` from the create-socket-app yet. You can install in with `npm i -g @socketsupply/socket` or using these instructions https://sockets.sh/#install
