### ISSUE TITLE
I'm getting an error when I run `yarn create socket-app [react | svelte | tonic | vanilla | vue]`

### ISSUE THREAD

**Issue by lamiazar** [socketsupply/create-socket-app#20]
I get this error message when I run any of the templates :
```
yarn create socket-app vanilla
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 0s 132ms

Initializing npm package...OK
Installing developer dependencies...
Unable to run npm install: Error: Command failed: npm install -D esbuild
npm ERR! code 1
npm ERR! path /home/lamia/Desktop/my-app/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! node:internal/errors:857
npm ERR!   const err = new Error(message);
npm ERR!               ^
npm ERR! 
npm ERR! Error: Command failed: /usr/bin/node /home/lamia/Desktop/my-app/node_modules/esbuild/bin/esbuild --version
npm ERR! node:internal/errors:478
npm ERR!     ErrorCaptureStackTrace(err);
npm ERR!     ^
npm ERR! 
npm ERR! TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /home/lamia/Desktop/my-app/node_modules/esbuild/bin/esbuild
npm ERR!     at new NodeError (node:internal/errors:387:5)
npm ERR!     at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:75:11)
npm ERR!     at defaultGetFormat (node:internal/modules/esm/get_format:117:38)
npm ERR!     at defaultLoad (node:internal/modules/esm/load:81:20)
npm ERR!     at nextLoad (node:internal/modules/esm/loader:163:28)
npm ERR!     at load$1 (file:///tmp/xfs-0d43b79d/dlx-7554/.pnp.loader.mjs:1455:12)
npm ERR!     at nextLoad (node:internal/modules/esm/loader:163:28)
npm ERR!     at ESMLoader.load (node:internal/modules/esm/loader:605:26)
npm ERR!     at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
npm ERR!     at new ModuleJob (node:internal/modules/esm/module_job:63:26) {
npm ERR!   code: 'ERR_UNKNOWN_FILE_EXTENSION'
npm ERR! }
npm ERR! 
npm ERR!     at checkExecSyncError (node:child_process:861:11)
npm ERR!     at Object.execFileSync (node:child_process:896:15)
npm ERR!     at validateBinaryVersion (/home/lamia/Desktop/my-app/node_modules/esbuild/install.js:97:28)
npm ERR!     at /home/lamia/Desktop/my-app/node_modules/esbuild/install.js:282:5 {
npm ERR!   status: 1,
npm ERR!   signal: null,
npm ERR!   output: [
npm ERR!     null,
npm ERR!     Buffer(0) [Uint8Array] [],
npm ERR!     Buffer(906) [Uint8Array] [
npm ERR!       110, 111, 100, 101,  58, 105, 110, 116, 101, 114, 110,  97,
npm ERR!       108,  47, 101, 114, 114, 111, 114, 115,  58,  52,  55,  56,
npm ERR!        10,  32,  32,  32,  32,  69, 114, 114, 111, 114,  67,  97,
npm ERR!       112, 116, 117, 114, 101,  83, 116,  97,  99, 107,  84, 114,
npm ERR!        97,  99, 101,  40, 101, 114, 114,  41,  59,  10,  32,  32,
npm ERR!        32,  32,  94,  10,  10,  84, 121, 112, 101,  69, 114, 114,
npm ERR!       111, 114,  32,  91,  69,  82,  82,  95,  85,  78,  75,  78,
npm ERR!        79,  87,  78,  95,  70,  73,  76,  69,  95,  69,  88,  84,
npm ERR!        69,  78,  83,  73,
npm ERR!       ... 806 more items
npm ERR!     ]
npm ERR!   ],
npm ERR!   pid: 7645,
npm ERR!   stdout: Buffer(0) [Uint8Array] [],
npm ERR!   stderr: Buffer(906) [Uint8Array] [
npm ERR!     110, 111, 100, 101,  58, 105, 110, 116, 101, 114, 110,  97,
npm ERR!     108,  47, 101, 114, 114, 111, 114, 115,  58,  52,  55,  56,
npm ERR!      10,  32,  32,  32,  32,  69, 114, 114, 111, 114,  67,  97,
npm ERR!     112, 116, 117, 114, 101,  83, 116,  97,  99, 107,  84, 114,
npm ERR!      97,  99, 101,  40, 101, 114, 114,  41,  59,  10,  32,  32,
npm ERR!      32,  32,  94,  10,  10,  84, 121, 112, 101,  69, 114, 114,
npm ERR!     111, 114,  32,  91,  69,  82,  82,  95,  85,  78,  75,  78,
npm ERR!      79,  87,  78,  95,  70,  73,  76,  69,  95,  69,  88,  84,
npm ERR!      69,  78,  83,  73,
npm ERR!     ... 806 more items
npm ERR!   ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lamia/.npm/_logs/2023-02-20T21_16_24_147Z-debug-0.log

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    ```

**Comment by lamiazar** [comment]
realted to #22
